services:
  api:
    build: .
    expose:
      - "${PORT:-8080}"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PORT=${PORT}

  client:
    build:
      context: ./client
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    expose:
      - "3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - api
